fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    archive:
      repo: "git://github.com/voxpupuli/puppet-archive.git"
  symlinks:
    java: "#{source_dir}"
